
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ALFA
 */
public class editPlanForm extends javax.swing.JFrame {

    Plan plan;
    AdminUI adminUI;

    /**
     * Creates new form editPlanForm
     */
    public editPlanForm(Plan plan, AdminUI adminUI) {
        this.plan = plan;
        this.adminUI = adminUI;
        initComponents();
        this.planIDField.setText(plan.getId() + "");
        this.planUserNameField.setText(plan.userName);
        this.modelField.setText(plan.getHandset().getModel());
        this.memorySizeField.setText(plan.getHandset().getMemorySize() + "");
        this.priceField.setText(plan.getHandset().getPrice() + "");
        this.internetQuotaField.setText(plan.internetQuota + "");
        this.OSComboBox.setSelectedItem(plan.getHandset().getType().toString());
        this.capLimitField.setText(plan.capLimit + "");
        this.dayField.setText(plan.getExpiryDate().getDay() + "");
        this.monthField.setText(plan.getExpiryDate().getMonth() + "");
        this.yearField.setText(plan.getExpiryDate().getYear() + "");
        if (plan instanceof PersonalPlan) {

            this.personalPlanChoice.setSelected(true);
            this.bussinesPlanChoice.setSelected(false);
            this.cityOrNoField.setText("City");
            this.cityOrNoField.setText(((PersonalPlan) plan).city);
            this.ABNField.setText("");
            this.ABNField.setVisible(false);
            this.ABNField.setVisible(false);
        } else {

            this.personalPlanChoice.setSelected(false);
            this.bussinesPlanChoice.setSelected(true);
            this.cityOrNoField.setText("Employee NO");
            this.cityOrNoField.setText(((BusinessPlan) plan).numberOfEmployees + "");
            this.ABNField.setText(((BusinessPlan) plan).ABN + "");
            this.ABNField.setVisible(true);
            this.ABNField.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        personalPlanChoice = new javax.swing.JRadioButton();
        bussinesPlanChoice = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        planIDField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        planUserNameField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        modelField = new javax.swing.JTextField();
        memorySizeField = new javax.swing.JTextField();
        OSComboBox = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        priceField = new javax.swing.JTextField();
        internetQuotaField = new javax.swing.JTextField();
        capLimitField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cityOrNoLable = new javax.swing.JLabel();
        dayField = new javax.swing.JTextField();
        monthField = new javax.swing.JTextField();
        yearField = new javax.swing.JTextField();
        cityOrNoField = new javax.swing.JTextField();
        clearButton = new javax.swing.JButton();
        ABNLabel = new javax.swing.JLabel();
        ABNField = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        personalPlanChoice.setText("PersonalPlan");
        personalPlanChoice.setEnabled(false);
        personalPlanChoice.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                personalPlanChoiceStateChanged(evt);
            }
        });
        personalPlanChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalPlanChoiceActionPerformed(evt);
            }
        });

        bussinesPlanChoice.setText("BussinesPlan");
        bussinesPlanChoice.setEnabled(false);

        jLabel9.setText("Plan ID");

        planIDField.setEnabled(false);

        jLabel10.setText("Username");

        planUserNameField.setEnabled(false);

        jLabel11.setText("Mobile Phone");

        jLabel12.setText("Model");

        jLabel13.setText("OS Type");

        jLabel14.setText("MemorySize");

        OSComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IOS", "Windows", "Android" }));
        OSComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OSComboBoxActionPerformed(evt);
            }
        });

        jLabel15.setText("Price");

        capLimitField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capLimitFieldActionPerformed(evt);
            }
        });

        jLabel16.setText("Internet Quota");

        jLabel17.setText("Cap Limit");

        jLabel18.setText("Expiry Date");

        jLabel19.setText("Day");

        jLabel20.setText("Month");

        jLabel21.setText("Year");

        cityOrNoLable.setText("City");

        clearButton.setForeground(new java.awt.Color(255, 0, 0));
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        ABNLabel.setText("ABN");

        ABNField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABNFieldActionPerformed(evt);
            }
        });

        updateButton.setForeground(new java.awt.Color(51, 255, 51));
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(updateButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel21)
                                            .addComponent(cityOrNoLable))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cityOrNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(dayField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                                .addComponent(monthField, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addComponent(yearField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(planIDField, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                                    .addComponent(planUserNameField)))
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(21, 21, 21)
                                            .addComponent(capLimitField))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel16)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(internetQuotaField))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel15)
                                            .addGap(52, 52, 52)
                                            .addComponent(priceField))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(modelField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(OSComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel14)
                                            .addGap(18, 18, 18)
                                            .addComponent(memorySizeField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(personalPlanChoice)
                                .addGap(18, 18, 18)
                                .addComponent(bussinesPlanChoice))
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(clearButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(ABNLabel)
                                .addGap(18, 18, 18)
                                .addComponent(ABNField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(205, 205, 205))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personalPlanChoice)
                    .addComponent(bussinesPlanChoice)
                    .addComponent(updateButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(planIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(planUserNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(OSComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memorySizeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(internetQuotaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(capLimitField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(dayField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(monthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(yearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityOrNoLable)
                    .addComponent(cityOrNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ABNLabel)
                    .addComponent(ABNField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void personalPlanChoiceStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_personalPlanChoiceStateChanged
        if (personalPlanChoice.isSelected()) {
            ABNField.setVisible(false);
            ABNLabel.setVisible(false);
            cityOrNoLable.setText("City");

        } else {
            ABNField.setVisible(true);
            ABNLabel.setVisible(true);
            cityOrNoLable.setText("Employee NO");
        }
    }//GEN-LAST:event_personalPlanChoiceStateChanged

    private void personalPlanChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalPlanChoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personalPlanChoiceActionPerformed

    private void OSComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OSComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OSComboBoxActionPerformed

    private void capLimitFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capLimitFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_capLimitFieldActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        planIDField.setText("");
        planUserNameField.setText("");
        modelField.setText("");
        memorySizeField.setText("");
        priceField.setText("");
        internetQuotaField.setText("");
        capLimitField.setText("");
        dayField.setText("");
        monthField.setText("");
        yearField.setText("");
        cityOrNoField.setText("");
        ABNField.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void ABNFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABNFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ABNFieldActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        try {
            String username = this.planUserNameField.getText();
            String model = this.modelField.getText();
            MobileType type = MobileType.valueOf(this.OSComboBox.getSelectedItem().toString());
            int size = Integer.parseInt(this.memorySizeField.getText());
            double price = Double.parseDouble(this.priceField.getText());
            int quota = Integer.parseInt(this.internetQuotaField.getText());
            int cap = Integer.parseInt(this.capLimitField.getText());
            int day = Integer.parseInt(this.dayField.getText());
            int month = Integer.parseInt(this.monthField.getText());
            int year = Integer.parseInt(this.yearField.getText());
            MyDate date = new MyDate(year, month, day);
            MobilePhone phone = new MobilePhone(model, type, size, price);
            this.plan.userName = username;
            this.plan.expiryDate = date;
            this.plan.handset = phone;
            this.plan.capLimit = cap;
            this.plan.internetQuota = quota;

            if (this.personalPlanChoice.isSelected()) {

                String city = this.cityOrNoField.getText();
                ((PersonalPlan) this.plan).city = city;
            } else {

                int numberOFEmployee = Integer.parseInt(this.cityOrNoField.getText());
                int ABN = Integer.parseInt(this.ABNField.getText());
                ((BusinessPlan) this.plan).numberOfEmployees = numberOFEmployee;
                ((BusinessPlan) this.plan).ABN = ABN;
            }
            JOptionPane.showMessageDialog(this, "Plan has been updated");
            this.adminUI.fillPlanTable();
            dispose();
        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ABNField;
    private javax.swing.JLabel ABNLabel;
    private javax.swing.JComboBox<String> OSComboBox;
    private javax.swing.JRadioButton bussinesPlanChoice;
    private javax.swing.JTextField capLimitField;
    private javax.swing.JTextField cityOrNoField;
    private javax.swing.JLabel cityOrNoLable;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField dayField;
    private javax.swing.JTextField internetQuotaField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField memorySizeField;
    private javax.swing.JTextField modelField;
    private javax.swing.JTextField monthField;
    private javax.swing.JRadioButton personalPlanChoice;
    private javax.swing.JTextField planIDField;
    private javax.swing.JTextField planUserNameField;
    private javax.swing.JTextField priceField;
    private javax.swing.JButton updateButton;
    private javax.swing.JTextField yearField;
    // End of variables declaration//GEN-END:variables
}
