
import java.util.ArrayList;
import java.util.InputMismatchException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ALFA
 */
public class LoginFrame extends javax.swing.JFrame {

    MobileCompany mobileCompany1 = new MobileCompany();

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        try {
            test();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }

        initComponents();
    }

    public void test() throws PlanException, PlanUserNameException {
        mobileCompany1 = new MobileCompany("NakhlCityt", "ar12",
                "ari00", TestCode.flatRate);
        // Creating phone Objects for adding to plans
        MobilePhone mobile1 = new MobilePhone("Galaxy S7", MobileType.Android, 4, 600);
        MobilePhone mobile2 = new MobilePhone("Iphone X", MobileType.IOS, 3, 300);
        MobilePhone mobile3 = new MobilePhone("pixel 4a", MobileType.Windows, 6, 500);
        MobilePhone mobile4 = new MobilePhone("huawei Y9prime", MobileType.Android, 4, 300);
        MobilePhone mobile5 = new MobilePhone("xiaomi 11 pro", MobileType.Android, 12, 900);
        // creating test plans objects
        PersonalPlan plan1 = new PersonalPlan("USR000000U", 3000000, mobile1, 2, 3, new MyDate(2028, 2, 3),
                "Paris");
        BusinessPlan plan2 = new BusinessPlan("USR000001U", 3000001, mobile2, 3, 2, new MyDate(2024, 7, 12), 4,
                5);
        PersonalPlan plan3 = new PersonalPlan("USR000002U", 3000002, mobile2, 9, 1, new MyDate(2025, 12, 7),
                "London");
        BusinessPlan plan4 = new BusinessPlan("USR000003U", 3000003, mobile1, 8, 6, new MyDate(2023, 7, 2), 1,
                2);
        BusinessPlan plan5 = new BusinessPlan("USR000004U", 3000004, mobile3, 15, 1, new MyDate(2027, 2, 3), 5,
                1);
        PersonalPlan plan6 = new PersonalPlan("USR000005U", 3000005, mobile3, 13, 12,
                new MyDate(2034, 10, 7),
                "Ohio");

        // Creat Users
        User user1 = new User("Ahmad", "1", 1, new Address(5, "Daneshladeh", "4", "Karaj"));
        User user2 = new User("Demitry", "1", 2, new Address(4, "Lenin", "5", "Fardis"));
        User user3 = new User("Arash", "1", 3, new Address(2, "Navab", "7", "Tehran"));
        User user4 = new User("Hirad", "1", 4, new Address(5, "Motahari", "6", "Tehran"));
        User user5 = new User("Ali", "1", 5, new Address(2, "Hoseini", "4", "karaj"));

        // Add Plan to our users in MobileCompany
        user1.addPlan(plan1);
        user1.addPlan(plan2);
        user1.addPlan(plan3);
        user2.addPlan(plan2);
        user2.addPlan(plan3);
        user3.addPlan(plan4);
        user4.addPlan(plan5);
        user4.addPlan(plan6);
        user5.addPlan(plan1);
        user5.addPlan(plan5);

        // Add Users to our mobile company
        mobileCompany1.addUser(user1);
        mobileCompany1.addUser(user2);
        mobileCompany1.addUser(user3);
        mobileCompany1.addUser(user4);
        mobileCompany1.addUser(user5);

        // Add Plan to our users in MobileCompany
//        UIMethods.addPlan(mobileCompany1, 1, plan1);
//        UIMethods.addPlan(mobileCompany1, 1, plan2);
//        UIMethods.addPlan(mobileCompany1, 1, plan3);
//        UIMethods.addPlan(mobileCompany1, 1, plan4);
//        UIMethods.addPlan(mobileCompany1, 2, plan6);
//        UIMethods.addPlan(mobileCompany1, 2, plan3);
//        UIMethods.addPlan(mobileCompany1, 2, plan1);
//        UIMethods.addPlan(mobileCompany1, 3, plan2);
//        UIMethods.addPlan(mobileCompany1, 3, plan5);
//        UIMethods.addPlan(mobileCompany1, 4, plan4);
//        UIMethods.addPlan(mobileCompany1, 4, plan5);
//        UIMethods.addPlan(mobileCompany1, 4, plan6);
//        UIMethods.addPlan(mobileCompany1, 5, plan2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userNameTextFrame = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logInButton = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        saveItem = new javax.swing.JMenuItem();
        loadItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userNameTextFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTextFrameActionPerformed(evt);
            }
        });

        jLabel1.setLabelFor(userNameTextFrame);
        jLabel1.setText("UserName");

        jLabel2.setLabelFor(passwordField);
        jLabel2.setText("Password");

        logInButton.setText("Log In");
        logInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInButtonActionPerformed(evt);
            }
        });

        fileMenu.setText("File");
        fileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuActionPerformed(evt);
            }
        });

        saveItem.setText("Save");
        saveItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveItemMouseClicked(evt);
            }
        });
        saveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveItem);

        loadItem.setText("Load");
        loadItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadItemMouseClicked(evt);
            }
        });
        loadItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadItemActionPerformed(evt);
            }
        });
        fileMenu.add(loadItem);

        jMenuBar1.add(fileMenu);

        jMenu1.setText("Users");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userNameTextFrame)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(logInButton))
                    .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                .addGap(181, 181, 181))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameTextFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(logInButton)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userNameTextFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTextFrameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTextFrameActionPerformed

    private void logInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInButtonActionPerformed
//        try {
        User user = null;
        try {
            user = this.mobileCompany1.userValidate(Integer.parseInt(userNameTextFrame.getText()), this.passwordField.getText());

        } catch (Exception e) {
        }

        if (user != null) {
            ArrayList<String> cities = this.mobileCompany1.populateDistinctCityNames();
            UserUI userUI = new UserUI(user, this, cities);
            userUI.setVisible(true);
            setVisible(false);

        } else if (mobileCompany1.validateAdmin(userNameTextFrame.getText(), this.passwordField.getText())) {
            AdminUI adminUI = new AdminUI(mobileCompany1, this);
            adminUI.setVisible(true);
            setVisible(false);

        } else {

            JOptionPane.showMessageDialog(this, "Username or password is wrong");
        }
        this.passwordField.setText("");
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, e);
//        }

    }//GEN-LAST:event_logInButtonActionPerformed

    private void fileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileMenuActionPerformed

    private void loadItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadItemActionPerformed
        try {
            mobileCompany1.load("savedCompany.bin");
            JOptionPane.showMessageDialog(this, "Loaded successfully");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_loadItemActionPerformed

    private void saveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveItemActionPerformed
        try {
            mobileCompany1.save("savedCompany.bin");
            JOptionPane.showMessageDialog(this, "Saved successfully");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_saveItemActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        String output = "";
        for (User user : this.mobileCompany1.getUsers().values()) {
            output = output + "username: " + user.getUserID() + " pass: " + user.getUserPassword() + "\n";
        }
        JOptionPane.showMessageDialog(this, output);
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        String output = "";
        output += "Admin:" + "\n" + "User Name: ar12   Password: ari00" + "\n";
        output += "Users:" + "\n";
        for (User user : this.mobileCompany1.getUsers().values()) {
            output = output + "ID: " + user.getUserID() + " Password: " + user.getUserPassword() + "\n";
        }
        JOptionPane.showMessageDialog(this, output);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void saveItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveItemMouseClicked
        String output = "";
        try {
            mobileCompany1.save("savedCompany.bin");
            JOptionPane.showMessageDialog(this, "Saved successfully");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        JOptionPane.showMessageDialog(this, output);    }//GEN-LAST:event_saveItemMouseClicked

    private void loadItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadItemMouseClicked
        String output = "";
        try {
            mobileCompany1.load("savedCompany.bin");
            JOptionPane.showMessageDialog(this, "Loaded successfully");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        JOptionPane.showMessageDialog(this, output);     }//GEN-LAST:event_loadItemMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem loadItem;
    private javax.swing.JButton logInButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JMenuItem saveItem;
    private javax.swing.JTextField userNameTextFrame;
    // End of variables declaration//GEN-END:variables
}
