public class PlanUserNameException extends Exception {
    String userName;

    public PlanUserNameException(String userName) {
        this.userName = userName;

    }

    public String toString() {
        return "The Plan UserName was not valid, and a new UserName (" + userName
                + ") is generated by the admin and assigned for the Plan.";
    }
}
