public class PlanException extends Exception {
    int ID;

    public PlanException(int ID) {
        this.ID = ID;

    }

    public String toString() {
        return "The Plan ID was not valid, and a new ID (" + ID
                + ") is generated by the admin and assigned for the Plan.";
    }
}
